### ISSUE TITLE
Difficulties with an import from a custom path

### ISSUE THREAD

**Issue by takluyver** [sampsyo/clusterfutures#14]
Some of my colleagues (cc @daviddoji) have got code where part of the work done inside clusterfutures is from a module imported from a path explicitly added to `sys.path`. This is a simplified sketch of the code:

```python
import cfut
import sys
sys.path.insert(0, "/some/path/to/folder/containing/modules")
from internal_module import some_func

def do_work():
    some_func()

with cfut.SlurmExecutor() as extor:
    fut = extor.submit(do_work)
```

This failed with an error `ModuleNotFoundError: No module named 'internal_module'`. Inspecting the code of clusterfutures, they realised that the `additional_setup_lines` option could be used for shell code (nice benefit of a small codebase!). So they used that to set `PYTHONPATH`. This was working until it suddenly stopped. After a lot of bafflement, we realised that a change in an outer system, beyond our control, was setting `SLURM_EXPORT_ENV` to a list of environment variables which didn't include PYTHONPATH. So the environment variable from the shell script didn't make it through `srun` to Python. Setting `SLURM_EXPORT_ENV=ALL` as well worked around that.

I don't have a great idea how this should work, but I don't think it should be necessary to fiddle with shell & environment variables. Various ideas:

- Add a parameter like `additional_import_paths` alongside `additional_setup_lines`, where you can pass filesystem paths to add to `sys.path` before the cloudpickle-d task data is loaded. Easy to implement, but still requires the user to set this explicitly.
- Replicate `sys.path` in the worker process before loading the task data? Seems handy for our use case, but I can imagine that sort of global, implicit change could get messy.
- Cloudpickle [can be set](https://github.com/cloudpipe/cloudpickle#overriding-pickles-serialization-mechanism-for-importable-constructs) to pickle functions from a given module by value, so it doesn't need to do the import when unpickling, i.e. `cloudpickle.register_pickle_by_value(internal_module)`. Maybe we should just be doing this in user code? It feels a bit like relying on an implementation detail of clusterfutures, although it's one that's unlikely to change in the near future.

**Comment by sampsyo** [comment]
Huh, that's an interesting situation! All your suggestions are very reasonable.

I don't have any objection to doing the `sys.path` preservation thing. It's sort of a baked-in assumption with clusterfutures that there's a shared filesystem and paths are meaningful on all the machines, so keeping `sys.path` equal on the submitter and the worker seems reasonable. (Maybe this behavior should be hidden behind a flag because it could cause unintended weirdness, but that wouldn't be so bad.)
