### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by padix-key** [sampsyo/clusterfutures#25]
Hi, I am interested in using this library, but found there is no license. This practically means that [all rights are reserved](https://opensource.stackexchange.com/a/1721). Is this by intention or just an oversight?

**Comment by takluyver** [comment]
We've got `license='MIT',` in the metadata in setup.py, so I'm 99% sure the lack of a license file is just an oversight.

@sampsyo any objection to adding a LICENSE file in the root of the repository?

**Comment by sampsyo** [comment]
Good call; thank you—I did intend to use MIT. I'll add it now!
