### ISSUE TITLE
Data is submitted with an old pickle protocol

### ISSUE THREAD

**Issue by tjader** [sampsyo/clusterfutures#3]
When cfut calls cloudpickle.dumps, the second argument is set to either True or False. I'm not sure what the intent was, but cloudpickle (v1.2.1 at least) interprets it as the pickle version to use so cfut will use either v1 (if the argument is True) or v0 (if it's False).
Given that both v0 and v1 are ancient and produce much larger binaries, I suggest cfut should default to protocol=None (which cloudpickle will assume to mean the pickle.DEFAULT_PROTOCOL (which is v4 since python 3.4).
Places where this happens currently
cfut.ClusterExecutor#submit
cfut.remote.worker (2 places)

**Comment by sampsyo** [comment]
Yep, sounds good to me! Please open a PR if you have a chance.
